index:
   path: /
   controller: App\Controller\ApiController::index
predictions:
   path: /predictions/{city}-{scale}-{date}
   controller: App\Controller\ApiController::getPredictions
   defaults:
      city: 'amsterdam'
      scale: 'Fahrenheit'
      date: null
city:
   path: /city/{city}
   controller: App\Controller\ApiController::getPredictionsByCity
   defaults:
      city: 'amsterdam'
