index:
   path: /
   controller: App\Controller\ApiController::index
test:
   path: /test
   controller: App\Controller\ApiController::test
city:
   path: /city/{city}
   controller: App\Controller\ApiController::getPredictionsByCity
   defaults:
      city: 'amsterdam'
scale:
   path: /scale/{scale}
   controller: App\Controller\ApiController::getPredictionsByScale
   defaults:
      scale: 'Fahrenheit'
date:
   path: /date/{date}
   controller: App\Controller\ApiController::getPredictionsByDate
   defaults:
      date: null