index:
   path: /
   controller: App\Controller\ApiController::index
predictions:
   path: /predictions/{city}-{date}-{scale}
   controller: App\Controller\ApiController::getPredictionsUi
   defaults:
      city: 'amsterdam'
      scale: 'Fahrenheit'
      date: null
view:
   path: /view/{city}-{date}-{scale}
   controller: App\Controller\ApiController::getPredictionsApi
   defaults:
      city: 'amsterdam'
      scale: 'Fahrenheit'
      date: null
view-provider:
   path: /view-provider/{city}-{date}-{scale}
   controller: App\Controller\ApiController::getPredictionsPerProvider
   defaults:
      city: 'amsterdam'
      scale: 'Fahrenheit'
      date: null
pageNotFound:
    path:  /{path}
    controller: App\Controller\PageNotFoundController:pageNotFound
    defaults:
        path: .*
